from setuptools import setup, find_packages

setup(
    name='project_team',
    version='1.0.0',
    packages=find_packages(where='src'),
    package_dir={'': 'src'},
    url='',
    license='MIT License',
    author='Grey Kuling',
    author_email='gkuling@gmail.com',
    description='',
    long_description="foo bar baz",
    install_requires=[
        'torch',
        'torchvision',
        'torchaudio',
        'pandas',
        'numpy',
        'tqdm',
        'scikit-image',
        'scikit-learn',
        'transformers',
        'tokenizers',
        'matplotlib',
        'statsmodels',
        'nltk',
        'chardet',
    ],
    python_requires='>=3.8',
)